[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_error = "2Zgt223CiUBbQY5vw21N5enanw3kSgCd8YP3UYFvGTZP"

[registry]
url = "https://api.apr.dev"

[provider]
url = "localhost:8899"
cluster = "Localnet"
wallet = "~/.config/solana/id.json"


# [test.validator]
# url = "localhost:8899"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

